### ISSUE TITLE
Image update?

### ISSUE THREAD

**Issue by netcarver** [adamxp12/ProcessWire-TfaWebAuthn#4]
Hi Adam,

Wondering if this might be better represented by a webauthn icon if a suitably licensed .svg file can be sourced and attributed. Perhaps something like the one here (license unchecked) https://raw.githubusercontent.com/duo-labs/webauthn.io/master/static/src/images/shield.svg

**Comment by adamxp12** [comment]
As far as I know the is no official logo. That logo as far as I can see is from Duo and just for their test site.

https://github.com/webauthn-open-source/webauthn-logos

These logos are maybe a better fit? but the image I use is more of an example for users who might not be used to it. They can recognise the fairly standard yubikey design

**Comment by netcarver** [comment]
Yeah, this is not critical at all, but the Yubikey idea, whilst applicable to nerds-like-us, might not be recognised by folks who are used to the fingerprint or phone/facial recognition.  Shame there's no real official logo.  Closing as there's no point wasting time on this if there's no good candidate.
