### ISSUE TITLE
Request reversion of my changes

### ISSUE THREAD

**Issue by netcarver** [adamxp12/ProcessWire-TfaWebAuthn#5]
@adamxp12 Looks like my PR was (and is) bad - my apologies - but recommend reverting to https://github.com/adamxp12/TfaWebAuthn/commit/a552786366d1b9848a330f7320e60d2c586c4d16

**Comment by adamxp12** [comment]
Just reverted. I dont really have the time to test this stuff but did read over it and didnt see any glaring issues before hence why I merged but I trust your judgement on reverting it
