### ISSUE TITLE
Error in init() unless functionsAPI enabled.

### ISSUE THREAD

**Issue by netcarver** [adamxp12/ProcessWire-TfaWebAuthn#7]
Looks like the `init()` method assumes the functionsAPI is enabled.

Changing L36 from `if(config()->version('3.0.165')) {` to `if($this->config->version('3.0.165')) {` seems to fix this for me.

**Comment by netcarver** [comment]
PR in for this one now.

**Comment by adamxp12** [comment]
Merged :)
